/*!
 * Author: Dolphin.Li
 * Date:11/25/2009
 * Description: 档案管理模块页面显示元素名称
 * Update History: none
 */
Ext.ns('Ext.ArchivesForm');
//Ext.ArchivesForm.ContactForm =  
Ext.ArchivesForm.ArchivesFormNl ={
		
		UserArchives: '用户档案',
		UsArCustomerNo: '客户编号',
		UsArCustomerName: '客户名称',
		UsArUserNo:'用户编号',
		UsArUserName:'用户名称',
		UsArDept:'单位',
		UsArUserType:'用户类型',
		UsArPowerSupplyStation :'供电所',
		UsArPowerSupplyLine :'供电线路',
		UsArTrade:'行业',
		UsArPowerCapacity:'受电容量',
		UsArPowerProperty:'用电属性',
		UsArMeasureFashion:'计量方式',
		UsArPowerSupplyVoltage:'供电电压',
		UsArPowerSupplyFashion:'供电方式',
		UsArAmmeterAreaNo:'抄表区码',
		UsArAmmeterDate:'抄表日',
		UsArDateOpened:'开户时间',
		UsArContact:'联系人',
		TransformerArchives:'变压器档案',
	    TrArGroupNo:'变压器组号',
	    TrArNo:'编号',
	    TrArModel:'型号',
	    TrArType:'类型',
	    TrArManufacturer :'制造厂家',
	    TrArNameplateCapacity:'铭牌容量',
	    TerminalArchives:'终端档案',
	    TeArBranchNo:'终端局号',
	    TeArLogicalAddress :'终端逻辑地址',
	    TeArManufacturerNo:'制造厂家编码',
	    TeArModel:'终端型号',
	    TeArType:'终端类型',
	    TeArSIMNo:'SIM卡号',
	    TeArMainAddress:'主通信地址',
	    TeArMessageAddress:'短信地址',
	    TeArAPN:'APN',
	    TeArConnection:'接线方式',
	    TeArStipulationType:'规约类型',
	    TeArCollectModel:'数据采集方式',
	    TeArHightPassword:'高权限密码',
	    TeArLowPassword:'低权限密码',
	    TeArCT:'CT',
	    TeArPT:'PT',
	    TeArInstallDate:'终端安装日期',
	    AmmeterArchives:'表计档案',
	    AmArBranchNo:'表计局号',
	    AmArManufacturerNo:'厂商编码',
	    AmArAmmeterType:'表类型',
	    AmArCollectModel:'接线方式',
	    AmArMainStipulation:'主规约',
	    AmArMStAddress:'主规约通信地址',
	    AmArMStPassword:'主规约通信密码',
	    AmArCT:'CT',
	    AmArPT:'PT',
	    AmArPulseCode:'脉冲常数',
	    AmArStoichiometricPointNo:'计量点编号',
	    AmArSelfMagnification:'自身倍率',
	    AmArDigits:'位数',
	    AmArPrecision :'精度',
	    AmArDateInstalled:'装出日期',
	    CollectorArchives:'采集器档案',
	    CoArBranchNo:'采集器局号',
	    CoArDeptNo:'单位编码',
	    CoArTerminalBranchNo:'终端局号',
	    CoArUserNo:'用户编号',
	    CoArModel:'采集器型号',
	    CoArOutDate:'出场日期',
	    CoArOutNo:'出场编号',
	    CoArManufacturerNo:'厂家编码',
	    CoArStorageDate:'入库日期',
	    CoArInstalledDate:'安装日期',
	    CoArAddress:'通讯地址',
	    CoArAddressMounted:'安装地址',
	    CoArType:'采集器类型',
	    CoArRunState:'运行状态',
	    CoArCommunicationState:'通讯状态',
	    CoArCommunicationPort:'通讯端口号'
}
